# shellcheck shell=bash
# Only continue in interactive shells.
case $- in
    *i*) ;;
    *) return ;;
esac

HISTCONTROL=ignoreboth:erasedups
HISTSIZE=10000
HISTFILESIZE=20000
HISTTIMEFORMAT='%F %T '

shopt -s histappend
PROMPT_COMMAND="history -a; history -n${PROMPT_COMMAND:+; $PROMPT_COMMAND}"

export EDITOR=nano
export VISUAL=nano

alias less='less -R'
alias grep='grep --color=auto'
alias ls='ls --color=auto'

if [[ -r /usr/share/bash-completion/bash_completion ]]; then

    # shellcheck disable=SC1091

    source /usr/share/bash-completion/bash_completion

fi

if command -v fzf >/dev/null 2>&1; then

    if [[ -r /usr/share/doc/fzf/examples/key-bindings.bash ]]; then

        # shellcheck disable=SC1091

        source /usr/share/doc/fzf/examples/key-bindings.bash

    fi

    if [[ -r /usr/share/doc/fzf/examples/completion.bash ]]; then

        # shellcheck disable=SC1091

        source /usr/share/doc/fzf/examples/completion.bash

    fi

fi

gpull() {
    git pull --rebase
}

gpush() {
    local message="${*:-Update}"

    git status || return 1

    printf '\nPress Enter to add, commit and push, or Ctrl-C to cancel...'
    read -r

    git add -A || return 1

    if ! git diff --cached --quiet; then
        git commit -m "$message" || return 1
    fi

    git push
}

###############################################################################

# History

###############################################################################

HISTCONTROL=ignoreboth:erasedups

HISTSIZE=10000

HISTFILESIZE=20000

HISTTIMEFORMAT='%F %T '

PROMPT_COMMAND='history -a; history -n'

# Expand history references such as !sudo, but require Enter before execution.

shopt -s histverify

###############################################################################

# Editor and aliases

###############################################################################

export EDITOR='nano'

export VISUAL='nano'

alias less='less -R'

alias grep='grep --color=auto'

alias diff='diff --color=auto'

alias ls='ls --color=auto'

alias m='less'
