// Managed by vnordh/bootstrap

Unattended-Upgrade::Mail "";
Unattended-Upgrade::MailReport "only-on-error";

Unattended-Upgrade::Remove-Unused-Kernel-Packages "true";
Unattended-Upgrade::Remove-New-Unused-Dependencies "true";
Unattended-Upgrade::Remove-Unused-Dependencies "true";

Unattended-Upgrade::Automatic-Reboot "${AUTOUPDATES_AUTOMATIC_REBOOT}";
Unattended-Upgrade::Automatic-Reboot-WithUsers "false";
Unattended-Upgrade::Automatic-Reboot-Time "${AUTOUPDATES_REBOOT_TIME}";
